[versions]
# Libraries
kotest = "5.5.4"
graphql-java = "18.3"
graphql-kickstart-spring-boot = "14.1.0"
commons-text = "1.10.0"
spring-boot = "3.0.0"
dgs = "5.4.3"

[libraries]
# BOMs
boms-spring-boot = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
boms-dgs = { module = "com.netflix.graphql.dgs:graphql-dgs-platform-dependencies", version.ref = "dgs" }

# Libraries
graphql-kickstart-spring-boot-starter = { module = "com.graphql-java-kickstart:graphql-spring-boot-starter", version.ref = "graphql-kickstart-spring-boot" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
graphql-java = { module = "com.graphql-java:graphql-java", version.ref = "graphql-java" }
tailrocks-maven-publish-conventions = { module = "com.tailrocks.gradle:maven-publish-conventions", version = "0.2.0" }
tailrocks-signing-conventions = { module = "com.tailrocks.gradle:signing-conventions", version = "0.2.0" }
tailrocks-kotlin-conventions = { module = "com.tailrocks.gradle:kotlin-conventions", version = "0.2.0" }
tailrocks-junit-conventions = { module = "com.tailrocks.gradle:junit-conventions", version = "0.2.0" }
kotest-runner-junit = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }

[plugins]
test-logger = { id = "com.adarshr.test-logger", version = "3.2.0" }
tailrocks-spotless = { id = "com.tailrocks.spotless", version = "0.2.0" }
tailrocks-java = { id = "com.tailrocks.java", version = "0.2.0" }
tailrocks-idea = { id = "com.tailrocks.idea", version = "0.2.1" }
tailrocks-versions = { id = "com.tailrocks.versions", version = "0.2.0" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.0" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
