spring:
  main:
    web-application-type: reactive
  output:
    ansi:
      enabled: always

graphql:
  graphiql:
    enabled: true
  datetime:
    scalars:
      date:
        scalarName: MyDate
      localDate:
        scalarName: MyLocalDate
